version: '3'
services:
  nginx:
    build: ./nginx_service/
    ports:
      - "1488:80"

    depends_on:
      - api
      - frontend

    volumes:
      - /srv/smilehackathon/static:/usr/share/nginx/html/static

  api:
    build: ./api_service/
    volumes:
      - ./api_service/:/app/

  frontend:
    build: ./frontend_service/
    command: npm run build
    volumes:
      - /srv/smilehackathon/static:/react_app/static
